### ISSUE TITLE
epic: tx history

### ISSUE THREAD

**Issue by arein** [WalletConnect/blockchain-api#317]
- [x] Scaffold API
- [x] Support pagination
- [x] Expose metrics in Grafana (tracked by #360)
- [x] Expand analytics to cover tx history calls (tracked by #362)
- [x] Update response format blocked on @0xAsimetriq to provide desired spec (current spec `curl -v "https://rpc.walletconnect.com/v1/account/0xf3ea39310011333095CFCcCc7c4Ad74034CABA63/history?projectId=b5dba79e421fd90af68d0a1006caf864" | jq .`) 
    Tracked by #339, #340
- [x] Cover in integration tests. 
    Added basic integration test [account_history_check](https://github.com/WalletConnect/blockchain-api/pull/340/files#diff-bd321c12cdc262812098945ace1b24fa4aa9c1bed12386c9922687ceff39e42cR69) in #340

**Comment by 0xAsimetriq** [comment]
Here is suggestion for some field re-naming and data structure flattening. Also, I am not seeing few key data points here:

1. Chain id data correlates to, if possible can we return it in caip format as part of the response below?
2. Zerion has more data on each of these it seems i.e. they show nft previews, protocol names (assume related to hash or from address), amount transacted , images for all involved assets (or nft picture), fee, exchange rate and perhaps something else I forgot. What is our strategy of exposing these, should I be making further requests to this data, if so to which endpoints? If we are caching these (i.e. confirmed transactions never change) maybe we can make these extra requests on the backend and append all this extra data to the response below? This way sub-sequent requests for history will come from cache and we only need to make 1 req client side.

```json
{
   "data":[
      {
         "id":"...",
         "type": "-> operationType",
         "hash": "...",
         "dateTime": "-> minedAt",
         "from": -> sentFrom",
         "to": "-> sentTo",
         "status": "...",
         "nonce": ""
      }
   ],
   "next":"WyIyMDIzLTA4LTA3VDA4OjQxOjE3WiIsImFmZDRjMmRhN2VmYzVlZjFhZjQ3MmMxMTAwZjM0NDU0Il0="
}
```

**Comment by arein** [comment]
1) good idea
2) yup my intention was to ask you which fields are missing in order to build the UI - which ones do you need @0xAsimetriq ?
3) at this point it's tied to Zerion - but should we add another provider we can change that and track for a cursor which provider it was with

**Comment by geekbrother** [comment]
> Below are designs for tx history, not sure if we can satisfy all cases, but assuming that we can:
> 
> 1. Fiat value of transaction
> 2. Crypto value of transaction (actions like swaps have 2 values)
> 3. Url(s) to token(s) images
> 4. Url(s) to nft image
> 5. NFT name / Collection name
> 6. ENS names when available?
> 
> <img alt="Screenshot 2023-09-12 at 14 37 17" width="765" src="https://user-images.githubusercontent.com/3154053/267315508-2981b845-43e9-4b2f-a662-6abe1e55c476.png">

Created #340 to expose additional information for transactions.

**Comment by stvnreaves** [comment]
> - [x] Scaffold API
> - [x] Support pagination
> - [ ] Expose metrics in Grafana
> - [ ] Expand analytics to cover tx history calls
> - [ ] Update response format blocked on @0xAsimetriq to provide desired spec (current spec `curl -v "https://rpc.walletconnect.com/v1/account/0xf3ea39310011333095CFCcCc7c4Ad74034CABA63/history?projectId=b5dba79e421fd90af68d0a1006caf864" | jq .`) 
>     Tracked by #339, #340
> - [ ] Cover in integration tests. 
>     Added basic integration test [account_history_check](https://github.com/WalletConnect/blockchain-api/pull/340/files#diff-bd321c12cdc262812098945ace1b24fa4aa9c1bed12386c9922687ceff39e42cR69) in #340

**Comment by geekbrother** [comment]
Closing this issue because all subtasks are done.
