### ISSUE TITLE
feat: block bots

### ISSUE THREAD

**Issue by arein** [WalletConnect/blockchain-api#323]
Blockchain APIs was built to support web3modal which is not used by bots. Hence, add bot protection such that bots don't consume our quotas.

- [ ] Set up AWS WAF Rule to get bot annotation (service is using an ALB)
- [ ] Track relevant bot parameters in analytics
- [ ] Analyze who is currently calling as bot
- [ ] Decide whether to allow bots via a flag in Cloud for certain projects
- [ ] Reject calls from bots
